# Problem 1 

In [4]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
a = np.random.randint(0,100, size=(1,5))
print(a)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
a.sort()
print(a)


[[76 26 39 97 70]]
[[26 39 70 76 97]]


# Problem 2

In [42]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
x = np.array([10,15,30,45,60])
print(x)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
y = np.arange(5,15,1)
print(y) 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
z = np.arange(50,100,5)
print(z)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
q = np.zeros(10)
print(q)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
q1 = np.ones(10)
print(q1)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
w = np.linspace(0,100,5)
print("w=", w)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
e = np.random.randint(10,30, size=(1,5))
print("e=",e)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
r = np.linspace(-1,1,10)
print("r=",r)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
m = np.random.randint(10,50, size=(3,5))
print("m=",m)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
m_sütun= m.sum(axis=0)
print(m_sütun, "sütunların toplamı.")
m_satır= m.sum(axis=1)
print(m_satır, "satırların toplamı.")
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
\

print(m.max(), "en büyük")
print(m.min(), "en küçük")
print(m.mean(), "ortalama")


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?



# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
k = np.arange(10,20,1)
print(k)
print(k[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(k[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(m[0], "m matrisi ilk satır")

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(m[1,2], "ikinci satır üçüncü sütundaki değer")

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(m[:,0], "tüm satırlardaki ilk eleman")

# 18- Üretilen matrisin her bir elemanının karesini alınız.
for i in m:
    a = i**2
    print(i, a)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
for i in m:
    if (i > 0).any():
        print(i, "pozitif sayılar")
        if (i%2 == 0):
            print(i, "çift pozitif sayılar")

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
w= [  0.  25.  50.  75. 100.]
e= [[20 25 25 26 24]]
r= [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
m= [[43 13 11 28 12]
 [10 11 28 43 32]
 [28 43 23 17 32]]
[81 67 62 88 76] sütunların toplamı.
[107 124 143] satırların toplamı.
43 en büyük
10 en küçük
24.933333333333334 ortalama
[10 11 12 13 14 15 16 17 18 19]
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[43 13 11 28 12] m matrisi ilk satır
28 ikinci satır üçüncü sütundaki değer
[43 10 28] tüm satırlardaki ilk eleman
[43 13 11 28 12] [1849  169  121  784  144]
[10 11 28 43 32] [ 100  121  784 1849 1024]
[28 43 23 17 32] [ 784 1849  529  289 1024]
[43 13 11 28 12] pozitif sayılar


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()