# Problem 1

In [15]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.random.randint(0,10, size=(1,5))
print(a)

# 3 - matris'in boyutunu öğrenin
print(a.shape)

# 4 - matris'i yeniden boyutlandırın


# 5 - matris'in boyut sayısını öğrenin
print(a.ndim)


[[2 0 1 8 0]]
(1, 5)
2


# Problem 2

In [24]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
a = np.array([1,3,5,7,9])
# 2 - Oluşturduğunuz matrisi parçalayın
b = np.split(a, [2,4])
print(b)
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([b[0],b[1],b[2]]))




[array([1, 3]), array([5, 7]), array([9])]
[1 3 5 7 9]


# Problem 3

In [29]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
y = np.random.randint(5,100 , size=(1,10))
print(y)

# 2 - matris'in özelliklerini inceleyin


[[44 88 46 57 90 82 68 14 55 88]]
